### ISSUE TITLE
Left sidebar doesn't show scrollbar at specific font sizes.

### ISSUE THREAD

**Issue by yashwithgm** [mdn/learning-area#606] opened 2023-03-26 05:02 UTC
On changing font-sizes, in some cases the scrollbar on the left sidebar disappears which make links to some articles unreachable. This also happens when the viewport width is 1200px or above.

![screenshot-no-scrollbar](https://user-images.githubusercontent.com/19564585/227756190-7fc8ae46-3c9b-4373-a519-702d5bf8d357.png)

While at some font sizes, the scrollbar on the left sidebar appears again.

![screenshot-scrollbar](https://user-images.githubusercontent.com/19564585/227756290-f79f4edd-c963-42d8-b7cf-6eb7f31f8451.png)

**Comment by teoli2003** [comment] 2023-03-26 05:58
Thank you! Duplicate of mdn/yari#8494

**Closed by teoli2003** 2023-03-26 05:58 UTC
