### ISSUE TITLE
Responsive Images on Android

### ISSUE THREAD

**Issue by Riczerq** [mdn/learning-area#239] opened 2020-07-13 06:14 UTC
Hello!

I tested the [responsive.html](http://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/responsive.html) on my android device and it is downloading the 800px image instead of the 480px. I have done different tests in other scenarios and it also gives the same result. It works properly on desktop.

My device esp:
Resolution: 1080x1920
DPR: 2.549999952316284
clientWidth: 424

**Comment by avivmu** [comment] 2020-07-14 06:51
Yeah you are right, the problem is with the elva-fairy image. I tested using both FF device responsive mode, and Chrome responsive mode (from my computer). The one with Chris _is_ loading the 480px width as you can see from the Network tab.

![image](https://user-images.githubusercontent.com/19804341/87393603-19c13180-c5b7-11ea-9546-77bc9f1abde7.png)

**Comment by Riczer** [comment] 2020-07-14 06:58
Exactly. Any ideas why this behavior happens with the elva-fairy image? Shouldn't the browser download the 480px wide image instead of the 800px image as it does on desktop mode?

**Comment by Riczer** [comment] 2020-07-14 07:00
Exactly. Any ideas why this behavior happens with the elva-fairy image? Shouldn't the browser download the 480px wide image instead of the 800px image as it does on desktop mode?

**Comment by Riczerq** [comment] 2020-07-14 07:02
Exactly. Any ideas why this behavior happens with the elva-fairy image? Shouldn't the browser download the 480px wide image instead of the 800px image as it does on desktop mode?

**Comment by avivmu** [comment] 2020-07-15 09:39
I checked again and now I think it's working as expected.
When the browser calculates which image to use, it considers also the DPR - device pixel ratio, not only the available width.
Because your DPR is ~ 2.5, the max-width that to use the smaller image is not 600px, but 600/2.5 = 240px. Since your device is more than that, it shows the bigger one.
You can test all of it from your computer using DevTools responsive mode.
DPR of 1 - works as expected:
1. 600px - smaller image:
![image](https://user-images.githubusercontent.com/19804341/87529381-988d9b80-c697-11ea-8d0e-c2163b1de74f.png)
2. 601px - bigger one:
![image](https://user-images.githubusercontent.com/19804341/87529560-da1e4680-c697-11ea-9860-5e308840ed2e.png)
Also see [this SO answer](https://stackoverflow.com/questions/51290584/responsive-img-gets-wrong-images-from-srcset) for more info
I agree that this info about DPR should be mentioned in the tutorial to avoid future confusin. @chrisdavidmills your opinion?

**Comment by Riczerq** [comment] 2020-07-15 23:35
Thank you very much for answering! 

I tried using a higher max-width (ex: `(max-width: 3000px)`)to see if the problem was related to that, but it always showed the 800px image. Then, I tried by reducing the length used if the media query was fullfilled (ex: `(max-width: 480px) 240px`) that seemed to work with a 2.0 DPR. The problem is that I can't use the custom width I want on both mobile and desktop and the other problem is that in the 2.0 DPR example I can't use a width higher than 309. If I use a `(max-width: 480px) 310px` it no longer uses the 480px image in any resolution.

DPR 2.0 using `(max-width: 480px) 309px`  - works as expected:

480px - downloading elva-fairy-480w

![image](https://user-images.githubusercontent.com/55520420/87609263-0ce43100-c6d0-11ea-80e9-0f78b557e8cf.png)

481px - downloading elva-fairy-800w

![image](https://user-images.githubusercontent.com/55520420/87609365-5b91cb00-c6d0-11ea-805e-48f865e8c03e.png)

DPR 2.0 using `(max-width: 480px) 310px` - not working as expected

200px - downloading elva-fairy-800w

![image](https://user-images.githubusercontent.com/55520420/87609476-aa3f6500-c6d0-11ea-9959-5b00c56c4429.png)

I don't know if it exist a better approach to make it work the same on both mobile and desktop, or if I'm missing something.

Full example: 

`<img
          srcset="elva-fairy-480w.jpg 480w, elva-fairy-800w.jpg 800w"
          sizes="(max-width: 480px) 309px, 800px"
          src="elva-fairy-800w.jpg"
          alt="Elva dressed as a fairy"
        />`

**Comment by avivmu** [comment] 2020-07-18 10:59
I still think there is no bug. Try asking on SO so people can guide you where is your wrong assumption.

**Comment by Riczerq** [comment] 2020-07-19 22:49
I don't think it's a bug either, but I can't understand the behavior with other DPRs. Thanks again for your help, I will try on OS. Should I close this issue?

**Comment by avivmu** [comment] 2020-07-20 05:22
You can wait until another one will step in to answer. It seems that the 309/310 settings are the browser threshold for these image widths for DPR 2.
If you will find more useful info on SO you can link to that thread and then close it.

**Comment by avivmu** [comment] 2020-07-24 11:42
@Riczerq any update on this? On FF 309px behaves the same as 310px (using always 800px)

**Comment by Riczer** [comment] 2020-07-24 21:15
Hi @avivmu ! No one has answered the question on SO yet. As soon as I find something or get an answer I will post it here.

**Comment by Riczerq** [comment] 2020-07-24 21:17
Hi @avivmu ! No one has answered the question on SO yet. As soon as I find something or get an answer I will post it here.

**Comment by KooXme** [comment] 2021-02-01 06:14
Index

**Comment by jacekkoziol** [comment] 2021-05-05 05:07
Does anyone has any answer for this?

**Comment by caugner** [comment] 2023-10-12 10:48
I took a look at this issue, and as was already pointed out:
1. The DPI is taken into consideration when choosing the right size.
2. The two photos on the page have different breakpoints:
    - The first photo has different sources for `< 800px` and `>= 800px` (or 400px with a DPR of 2).
    - The second photo has different sources for `<= 600 px` and `> 600px` (or 300px with a DPR of 2).

The examples is therefore working as expected (albeit slightly confusing), so I'm going ahead and close this issue as wontfix.

**Closed by caugner** 2023-10-12 10:48 UTC
Labels: question
