### ISSUE TITLE
MDN Website dark mode.

### ISSUE THREAD

**Issue by MJP8** [mdn/learning-area#351] opened 2021-03-22 02:42 UTC
I use dark-themed GitHub and Monokai theme text editor, and when I open the MDN website my eyes have to adjust to the light. I  think there should be a dark mode for MDN too.

**Comment by chrisdavidmills** [comment] 2021-03-22 09:07
Hi there @MJP8 !

Thank you for sending us your thoughts about this. We have received this request (or similar) several times, and I agree that having a dark theme on MDN would be nice. But our dev team is very small and very busy, so at the moment they don't have time to implement this.

We have a discussion thread open to record ideas about this at https://github.com/mdn/yari/discussions/2539 — the yari repo is where our platform code is kept, so this is the best place to file such requests. Please feel free to go to the linked discussion and add your vote/ideas.

I'm closing this issue as a duplicate of the above discussion, but it is still great to have this to add weight to the dark mode requests. Thanks again for contributing.

**Closed by chrisdavidmills** 2021-03-22 09:07 UTC

**Comment by MJP8** [comment] 2021-03-22 12:15
Alright @chrisdavidmills.
