### ISSUE TITLE
html/forms/html-form-structure/payment-form.html STYLING ISSUE

### ISSUE THREAD

**Issue by vvronskyFX** [mdn/learning-area#609] opened 2023-04-11 04:47 UTC
Inside the MDN Learning area [article](https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form), The iframe source links to https://live-samples.mdn.mozilla.net/en-US/docs/Learn/Forms/How_to_structure_a_web_form/_sample_.a_payment_form.html that seems to be from an old version of the page.

Rather than looking like this:
![image](https://user-images.githubusercontent.com/64465297/231058588-14c95728-8bd5-43c6-bacf-b992374565c0.png)

The page looks like this:
![image](https://user-images.githubusercontent.com/64465297/231058661-198edcc3-ba02-44e3-8e9d-90ffc6c04c7d.png)

Note the spacing differences in both screenshots. 

Here's what I see in the browser inspect. The links to the source and the iframe are different. 
![Screenshot 2023-04-11 at 12 50 39 AM](https://user-images.githubusercontent.com/64465297/231059616-8962e287-e607-4b8b-a3b3-f8513d39e79c.png)

**Comment by habeebmoosa** [comment] 2023-04-12 17:34
I want to work on this issue. So could you assign it to me?

**Comment by vvronskyFX** [comment] 2023-04-21 06:02
> 

Hey @habeebmoosa I'm not sure how to assign this.

**Comment by marlatte** [comment] 2023-06-16 16:29
I noticed the same thing. The problem is in the `payment-form.css` file, where `label span` (line 23) applies the styling to the label's contents instead of the whole label. I got it to look nicer by changing this the rule to `p label`, though I'm sure there's more than one way to do it.

**Closed** 2023-10-27 13:52 UTC
Labels: effort: small, area: HTML
