### ISSUE TITLE
Is this if else check valid?

### ISSUE THREAD

**Issue by Hasy7201** [mdn/learning-area#360] opened 2021-04-28 23:57 UTC
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Object-oriented JavaScript class further exercises</title>
  </head>

  <body>
    <p>This example requires you to enter commands in your browser's JavaScript console (see <a href="https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools">What are browser developer tools</a> for more information).</p>

  </body>

    <script>
      function Person(first, last, age, gender, interests) {
        this.name = {
          'first': first,
          'last' : last
        };
        this.age = age;
        this.gender = gender;
        this.interests = interests;
        this.bio = function() {
          // First define a string, and make it equal to the part of
          // the bio that we know will always be the same.
          var string = this.name.first + ' ' + this.name.last + ' is ' + this.age + ' years old. ';
          // define a variable that will contain the pronoun part of
          // the second sentence
          var pronoun;
          var m = "M" || "m";
          var f = "F" || "f";

          // check what the value of gender is, and set pronoun
          // to an appropriate value in each case
          if(this.gender.charAt() === m) {
            pronoun = 'He likes ';
          } else if(this.gender.charAt() === f) {
            pronoun = 'She likes ';
          } else {
            pronoun = 'They like ';
          }

          // add the pronoun string on to the end of the main string
          string += pronoun;

          // use another conditional to structure the last part of the
          // second sentence depending on whether the number of interests
          // is 1, 2, or 3
          if(this.interests.length === 1) {
            string += this.interests[0] + '.';
          } else if(this.interests.length === 2) {
            string += this.interests[0] + ' and ' + this.interests[1] + '.';
          } else {
            // if there are more than 2 interests, we loop through them
            // all, adding each one to the main string followed by a comma,
            // except for the last one, which needs an and & a full stop
            for(var i = 0; i < this.interests.length; i++) {
              if(i === this.interests.length - 1) {
                string += 'and ' + this.interests[i] + '.';
              } else {
                string += this.interests[i] + ', ';
              }
            }
          }

          // finally, with the string built, we alert() it
          alert(string);
        };
        this.greeting = function() {
          alert('Hi! I\'m ' + this.name.first + '.');
        };
      };

      let person1 = new Person('Tammi', 'Smith', 32, 'neutral', ['music', 'skiing', 'kickboxing']);
    </script>
</html>

**Comment by Hasy7201** [comment] 2021-04-29 00:07
Can we assign value to a variable like: 

     var m = "M" || "m";
      var f = "F" || "f";

      // check what the value of gender is, and set pronoun
      // to an appropriate value in each case
      if(this.gender.charAt() === m) {
        pronoun = 'He likes ';
      } else if(this.gender.charAt() === f) {
        pronoun = 'She likes ';
      } else {
        pronoun = 'They like ';
      }

**Comment by postmeback** [comment] 2023-06-05 09:25
I think, here we have to use `keycode`.

**Comment by caugner** [comment] 2023-10-13 14:27
It looks like the issue is about this example:

https://github.com/mdn/learning-area/blob/c754e63586d8d897ebee120fe4dcd320e1eefef1/javascript/oojs/advanced/oojs-class-prototype.html#L29-L84

**Comment by dipikabh** [comment] 2023-11-03 19:37
Hello @Hasy7201, regarding your question in your [comment](https://github.com/mdn/learning-area/issues/360#issuecomment-828857384):

- The lines `var m = "M" || "m";` and `var f = "F" || "f";` will return the first true value, that is, "M" and "F" because of the OR (`||`) operator. This is perhaps not what you intend with those lines.
- `this.gender.charAt()` is not correct. [charAt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charAt#syntax) always needs an index like `charAt(0)`.

Since there is no bug in the documented code, I am closing this issue. Please feel free to reach out to us and our community with any questions on our [Discord server](https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels#discord_server). Thanks for using MDN!

**Closed by dipikabh** 2023-11-03 19:37 UTC
Labels: area: JavaScript
